[project]
name = "posthog-mcp-python"
version = "0.1.0"
description = "Python implementation of the PostHog Model Context Protocol (MCP) server"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    { name = "PostHog", email = "hey@posthog.com" },
]
dependencies = [
    "pydantic>=2.0.0",
]

[dependency-groups]
dev = [
    "datamodel-code-generator[http]>=0.25.0",
    "ruff>=0.1.0", 
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["."]

[tool.ruff]
target-version = "py311"
line-length = 100
indent-width = 4

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings  
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]
ignore = [
    "E501", # line too long
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.uv]
dev-dependencies = []